/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author andre
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuLivros = new javax.swing.JMenu();
        menuCadastroLivro = new javax.swing.JMenu();
        itemMenuCadastroLivro = new javax.swing.JMenuItem();
        itemMeniCadastroGenero = new javax.swing.JMenuItem();
        itemMenuCadastroEditora = new javax.swing.JMenuItem();
        menuListarLivro = new javax.swing.JMenu();
        itemMenuListarLivros = new javax.swing.JMenuItem();
        menuLeitores = new javax.swing.JMenu();
        menuCadastroLeitor = new javax.swing.JMenu();
        itemMenuCadastrarLeitor = new javax.swing.JMenuItem();
        menuHistorico = new javax.swing.JMenu();
        itemMenuCriarHistorico = new javax.swing.JMenuItem();
        itemMenuListarHistoricos = new javax.swing.JMenuItem();
        menuAvaliacoes = new javax.swing.JMenu();
        itemMenuAvaliarLivro = new javax.swing.JMenuItem();
        itemMenuListarAvaliacoes = new javax.swing.JMenuItem();
        itemMenuAdicionarLivro = new javax.swing.JMenuItem();
        menuAutores = new javax.swing.JMenu();
        itemMenuCadastroAutor = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        itemMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLivros.setText("Livros");

        menuCadastroLivro.setText("Cadastro");

        itemMenuCadastroLivro.setText("Cadastrar Livro");
        itemMenuCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroLivroActionPerformed(evt);
            }
        });
        menuCadastroLivro.add(itemMenuCadastroLivro);

        itemMeniCadastroGenero.setText("Cadastrar Gênero Literário");
        itemMeniCadastroGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMeniCadastroGeneroActionPerformed(evt);
            }
        });
        menuCadastroLivro.add(itemMeniCadastroGenero);

        itemMenuCadastroEditora.setText("Cadastrar Editora");
        itemMenuCadastroEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroEditoraActionPerformed(evt);
            }
        });
        menuCadastroLivro.add(itemMenuCadastroEditora);

        menuLivros.add(menuCadastroLivro);

        menuListarLivro.setText("Listar");

        itemMenuListarLivros.setText("Listar livros");
        itemMenuListarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuListarLivrosActionPerformed(evt);
            }
        });
        menuListarLivro.add(itemMenuListarLivros);

        menuLivros.add(menuListarLivro);

        jMenuBar1.add(menuLivros);

        menuLeitores.setText("Leitores");
        menuLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeitoresActionPerformed(evt);
            }
        });

        menuCadastroLeitor.setText("Cadastro");

        itemMenuCadastrarLeitor.setText("Cadastrar Leitor");
        itemMenuCadastrarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarLeitorActionPerformed(evt);
            }
        });
        menuCadastroLeitor.add(itemMenuCadastrarLeitor);

        menuLeitores.add(menuCadastroLeitor);

        menuHistorico.setText("Histórico de Leitura");

        itemMenuCriarHistorico.setText("Criar Histórico");
        itemMenuCriarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCriarHistoricoActionPerformed(evt);
            }
        });
        menuHistorico.add(itemMenuCriarHistorico);

        itemMenuListarHistoricos.setText("Listar Históricos");
        itemMenuListarHistoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuListarHistoricosActionPerformed(evt);
            }
        });
        menuHistorico.add(itemMenuListarHistoricos);

        menuLeitores.add(menuHistorico);

        menuAvaliacoes.setText("Avaliações");

        itemMenuAvaliarLivro.setText("Avaliar Livro");
        itemMenuAvaliarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAvaliarLivroActionPerformed(evt);
            }
        });
        menuAvaliacoes.add(itemMenuAvaliarLivro);

        itemMenuListarAvaliacoes.setText("Listar avaliações");
        itemMenuListarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuListarAvaliacoesActionPerformed(evt);
            }
        });
        menuAvaliacoes.add(itemMenuListarAvaliacoes);

        menuLeitores.add(menuAvaliacoes);

        itemMenuAdicionarLivro.setText("Adicionar Livro à Estante");
        itemMenuAdicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAdicionarLivroActionPerformed(evt);
            }
        });
        menuLeitores.add(itemMenuAdicionarLivro);

        jMenuBar1.add(menuLeitores);

        menuAutores.setText("Autores");

        itemMenuCadastroAutor.setText("Cadastrar Autor");
        itemMenuCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroAutorActionPerformed(evt);
            }
        });
        menuAutores.add(itemMenuCadastroAutor);

        jMenuBar1.add(menuAutores);

        menuOpcoes.setText("Opções");
        menuOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcoesActionPerformed(evt);
            }
        });

        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(itemMenuSair);

        jMenuBar1.add(menuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcoesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuOpcoesActionPerformed

    private void menuLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeitoresActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuLeitoresActionPerformed

    private void itemMenuCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroAutorActionPerformed
        // TODO add your handling code here:
        new FormCadastroAutor().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroAutorActionPerformed

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroLivroActionPerformed
        // TODO add your handling code here:
        new FormCadastroLivro().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroLivroActionPerformed

    private void itemMeniCadastroGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMeniCadastroGeneroActionPerformed
        // TODO add your handling code here:
        new FormCadastroGenero().setVisible(true);
    }//GEN-LAST:event_itemMeniCadastroGeneroActionPerformed

    private void itemMenuCadastroEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroEditoraActionPerformed
        // TODO add your handling code here:
        new FormCadastroEditora().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroEditoraActionPerformed

    private void itemMenuListarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuListarLivrosActionPerformed
        // TODO add your handling code here:
        new FormListarLivros().setVisible(true);
    }//GEN-LAST:event_itemMenuListarLivrosActionPerformed

    private void itemMenuCriarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCriarHistoricoActionPerformed
        // TODO add your handling code here:
        new FormHistorico().setVisible(true);
    }//GEN-LAST:event_itemMenuCriarHistoricoActionPerformed

    private void itemMenuListarHistoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuListarHistoricosActionPerformed
        // TODO add your handling code here:
        new FormListarHistoricos().setVisible(true);
    }//GEN-LAST:event_itemMenuListarHistoricosActionPerformed

    private void itemMenuCadastrarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarLeitorActionPerformed
        // TODO add your handling code here:
        new FormCadastroLeitor().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarLeitorActionPerformed

    private void itemMenuListarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuListarAvaliacoesActionPerformed
        // TODO add your handling code here:
        new FormListarAvaliacoes().setVisible(true);
    }//GEN-LAST:event_itemMenuListarAvaliacoesActionPerformed

    private void itemMenuAvaliarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAvaliarLivroActionPerformed
        // TODO add your handling code here:
        new FormAvaliacao().setVisible(true);
    }//GEN-LAST:event_itemMenuAvaliarLivroActionPerformed

    private void itemMenuAdicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAdicionarLivroActionPerformed
        // TODO add your handling code here:
        new FormAdicionarLivroEstante().setVisible(true);
    }//GEN-LAST:event_itemMenuAdicionarLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMeniCadastroGenero;
    private javax.swing.JMenuItem itemMenuAdicionarLivro;
    private javax.swing.JMenuItem itemMenuAvaliarLivro;
    private javax.swing.JMenuItem itemMenuCadastrarLeitor;
    private javax.swing.JMenuItem itemMenuCadastroAutor;
    private javax.swing.JMenuItem itemMenuCadastroEditora;
    private javax.swing.JMenuItem itemMenuCadastroLivro;
    private javax.swing.JMenuItem itemMenuCriarHistorico;
    private javax.swing.JMenuItem itemMenuListarAvaliacoes;
    private javax.swing.JMenuItem itemMenuListarHistoricos;
    private javax.swing.JMenuItem itemMenuListarLivros;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAutores;
    private javax.swing.JMenu menuAvaliacoes;
    private javax.swing.JMenu menuCadastroLeitor;
    private javax.swing.JMenu menuCadastroLivro;
    private javax.swing.JMenu menuHistorico;
    private javax.swing.JMenu menuLeitores;
    private javax.swing.JMenu menuListarLivro;
    private javax.swing.JMenu menuLivros;
    private javax.swing.JMenu menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
